### ISSUE TITLE
Araquanid's cry is missing

### ISSUE THREAD

**Issue by LOuroboros** [BuffelSaft/decomp_resources#1]
This was originally noticed by UltimaSoul in DizzyEgg's project.
For reference, I grabbed the cry from **[the Pokémon Showdown repository](https://play.pokemonshowdown.com/audio/cries/src/)** and converted it to .aif, in case you want to reuse it here, @BuffelSaft.
https://github.com/DizzyEggg/pokeemerald/pull/190

The cries of Meltan and Melmetal are also missing, but since they're in a limbo like state where they don't officially belong to a specific generation, it's understandable. Then again, I think they majority of the fanbase considers them a part of Gen. VII?
It probably wouldn't hurt to drop their cries in the "cries" folder, at least.

**Comment by BuffelSaft** [comment]
Don't know how that happened, but it's fixed now - thanks for letting me know!

I've also added cries for Meltan and Melmetal to the Gen VII cries folder.
